export {
  Phone as Phone,
  LogOut as Logout,
  Upload as Upload_Action,
  CircleAlert as Error,
  FileText as Report,
  House as Home,
  ArrowLeft as ArrowL,
  ArrowRight as ArrowR,
  CloudUpload as Upload,
  Search as Search,
  Menu as Menu,
  UserRound as Patients,
  Hourglass as Years_of_Experience,
  VenusAndMars as Gender,
  Calendar1 as Age,
  CircleCheckBig as Success,
  IdCard as ID,
  FileBadge as License_Number,
  FileUp as Upload_File,
  Image as Img,
  ChevronRight,
  ChevronDown as Arrowlist,
  Eye,
  EyeOff,
} from "lucide-react";
